DIRS = core
DIRNAME = versions
BUILDDIR = _build

.PHONY: all
all:
	mkdir -p $(BUILDDIR)/html/$(DIRNAME)
	cp -R $(DIRS) $(BUILDDIR)/html/$(DIRNAME)/

.PHONY: WD-tar
WD-tar:

.PHONY: WD-echidna
WD-echidna:

.PHONY: WD-echidna-CI
WD-echidna-CI:

.PHONY: diff
diff:

.PHONY: clean
clean:
