== Parsing...
== Elaboration...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

== IL Validation...
== Running pass ite...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

== IL Validation after pass ite...
== Running pass typefamily-removal...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

== IL Validation after pass typefamily-removal...
== Running pass remove-indexed-types...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

== IL Validation after pass remove-indexed-types...
== Running pass totalize...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

== IL Validation after pass totalize...
== Running pass else...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

== IL Validation after pass else...
== Running pass uncase-removal...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

== IL Validation after pass uncase-removal...
== Running pass sideconditions...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- if (|`m**`| = |`n***`|)
    -- (if (|`m*`| = |`n**`|))+{`m*` <- `m**`, `n**` <- `n***`}
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

== IL Validation after pass sideconditions...
== Running pass sub-expansion...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- if (|`m**`| = |`n***`|)
    -- (if (|`m*`| = |`n**`|))+{`m*` <- `m**`, `n**` <- `n***`}
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

== IL Validation after pass sub-expansion...
== Running pass sub...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- if (|`m**`| = |`n***`|)
    -- (if (|`m*`| = |`n**`|))+{`m*` <- `m**`, `n**` <- `n***`}
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

== IL Validation after pass sub...
== Running pass alias-demut...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- if (|`m**`| = |`n***`|)
    -- (if (|`m*`| = |`n**`|))+{`m*` <- `m**`, `n**` <- `n***`}
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

== IL Validation after pass alias-demut...
== Running pass improve-ids...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule mk_TestNestedIter{n_lst_lst_lst : nat***, m_lst_lst : nat**}:
    `%|-%`(n_lst_lst_lst, m_lst_lst)
    -- if (|m_lst_lst| = |n_lst_lst_lst|)
    -- (if (|m_lst| = |n_lst_lst|))+{m_lst <- m_lst_lst, n_lst_lst <- n_lst_lst_lst}
    -- (if (|n_lst| = m))*{m <- m_lst, n_lst <- n_lst_lst}+{m_lst <- m_lst_lst, n_lst_lst <- n_lst_lst_lst}

== IL Validation after pass improve-ids...
== Complete.
