== Parsing...
== Elaboration...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

== IL Validation...
== Running pass typefamily-removal...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

== IL Validation after pass typefamily-removal...
== Running pass remove-indexed-types...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

== IL Validation after pass remove-indexed-types...
== Running pass totalize...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

== IL Validation after pass totalize...
== Running pass else...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

== IL Validation after pass else...
== Running pass sideconditions...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- if (|`m**`| = |`n***`|)
    -- (if (|`m*`| = |`n**`|))+{`m*` <- `m**`, `n**` <- `n***`}
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

== IL Validation after pass sideconditions...
== Running pass sub...

;; test.spectec
relation HasSize: `%|-%`(nat, nat)

;; test.spectec
relation TestNestedIter: `%|-%`(nat***, nat**)
  ;; test.spectec
  rule _{`n***` : nat***, `m**` : nat**}:
    `%|-%`(n*{n <- `n*`}*{`n*` <- `n**`}+{`n**` <- `n***`}, m*{m <- `m*`}+{`m*` <- `m**`})
    -- if (|`m**`| = |`n***`|)
    -- (if (|`m*`| = |`n**`|))+{`m*` <- `m**`, `n**` <- `n***`}
    -- (if (|n*{n <- `n*`}| = m))*{m <- `m*`, `n*` <- `n**`}+{`m*` <- `m**`, `n**` <- `n***`}

== IL Validation after pass sub...
== Complete.
