(module
  (func "empty")

  (func "value-nop" (nop))
  (func "value-drop" (i32.const 1))
  (func "value-block-nop" (block (i32.const 1) (nop)))
  (func "value-block-drop" (block (nop) (i32.const 1)))

  (func "return" (return))
  (func "return-nop" (return (nop)))
  (func "return-drop" (return (i32.const 1)))
  (func "return-block-nop" (return (block (i32.const 1) (nop))))
  (func "return-block-drop" (return (block (nop) (i32.const 1))))

  (func "param" (param i32) (i32.eqz (get_local 0)))
  (func "params" (param i32 f64)
    (i32.eqz (get_local 0)) (f64.neg (get_local 1))
  )
  (func "param-param" (param i32) (param f64)
    (i32.eqz (get_local 0)) (f64.neg (get_local 1))
  )
  (func "params-params" (param i32 f32) (param i32) (param f64 i64)
    (i32.eqz (get_local 0)) (f32.neg (get_local 1)) (i32.eqz (get_local 2))
    (f64.neg (get_local 3)) (i64.eqz (get_local 4))
  )

  (func "result" (result i32) (i32.const 1))

  (func "local" (local i32) (i32.eqz (get_local 0)))
  (func "locals" (local i32 f64 i64)
    (i32.eqz (get_local 0)) (f64.neg (get_local 1)) (i64.eqz (get_local 2))
  )
  (func "local-local" (local i32) (local f64)
    (i32.eqz (get_local 0)) (f64.neg (get_local 1))
  )
  (func "locals-locals" (local i32 f32) (local i32) (local f64 i64)
    (i32.eqz (get_local 0)) (f32.neg (get_local 1)) (i32.eqz (get_local 2))
    (f64.neg (get_local 3)) (i64.eqz (get_local 4))
  )

  (func "param-result" (param i32) (result i32) (i32.eqz (get_local 0)))
  (func "params-result" (param i32 f64) (result i32)
    (f64.neg (get_local 1)) (i32.eqz (get_local 0))
  )
  (func "param-param-result" (param i32) (param f64) (result i32)
    (f64.neg (get_local 1)) (i32.eqz (get_local 0))
  )

  (func "result-local" (result i32) (local i32) (i32.eqz (get_local 0)))
  (func "result-locals" (result i32) (local i32 f64)
    (f64.neg (get_local 1)) (i32.eqz (get_local 0))
  )
  (func "result-local-local" (result i32) (local i32) (local f64)
    (f64.neg (get_local 1)) (i32.eqz (get_local 0))
  )

  (func "param-local" (param i32) (local f64)
    (i32.eqz (get_local 0)) (f64.neg (get_local 1))
  )
  (func "params-local" (param i32 i64) (local f64)
    (i32.eqz (get_local 0)) (i64.eqz (get_local 1)) (f64.neg (get_local 2))
  )
  (func "param-locals" (param i32) (local i64 f64)
    (i32.eqz (get_local 0)) (i64.eqz (get_local 1)) (f64.neg (get_local 2))
  )
  (func "params-locals" (param f32 i32) (local i64 f64)
    (f32.neg (get_local 0)) (i32.eqz (get_local 1))
    (i64.eqz (get_local 2)) (f64.neg (get_local 3))
  )
  (func "param-params-locals-local" (param f32) (param i32 f32) (local i64 f64) (local i32)
    (f32.neg (get_local 0)) (i32.eqz (get_local 1)) (f32.neg (get_local 2))
    (i64.eqz (get_local 3)) (f64.neg (get_local 4)) (i32.eqz (get_local 5))
  )

  (func "param-result-local" (param i32) (result f64) (local f64)
    (i32.eqz (get_local 0)) (f64.neg (get_local 1))
  )
  (func "params-params-result-locals-locals"
    (param i32 i64) (param f32 f64) (result i32)
    (local i32 f64) (local i64 f32 i32)
    (i32.eqz (get_local 0)) (i64.eqz (get_local 1)) (f32.neg (get_local 2))
    (f64.neg (get_local 3)) (i32.eqz (get_local 4)) (f64.neg (get_local 5))
    (i64.eqz (get_local 6)) (f32.neg (get_local 7)) (i32.eqz (get_local 8))
  )
)

(assert_return (invoke "empty"))

(assert_return (invoke "value-nop"))
(assert_return (invoke "value-drop"))
(assert_return (invoke "value-block-nop"))
(assert_return (invoke "value-block-drop"))

(assert_return (invoke "return"))
(assert_return (invoke "return-nop"))
(assert_return (invoke "return-drop"))
(assert_return (invoke "return-block-nop"))
(assert_return (invoke "return-block-drop"))

(assert_return (invoke "param" (i32.const 1)))
(assert_return (invoke "params" (i32.const 1) (f64.const 0)))
(assert_return (invoke "param-param" (i32.const 1) (f64.const 0)))
(assert_return (invoke "params-params" (i32.const 1) (f32.const 0) (i32.const 1) (f64.const 0) (i64.const 1)))

(assert_return (invoke "result") (i32.const 1))

(assert_return (invoke "local"))
(assert_return (invoke "locals"))
(assert_return (invoke "local-local"))
(assert_return (invoke "locals-locals"))

(assert_return (invoke "param-result" (i32.const 1)) (i32.const 0))
(assert_return (invoke "params-result" (i32.const 1) (f64.const 0)) (i32.const 0))
(assert_return (invoke "param-param-result" (i32.const 1) (f64.const 0)) (i32.const 0))

(assert_return (invoke "result-local") (i32.const 1))
(assert_return (invoke "result-locals" ) (i32.const 1))
(assert_return (invoke "result-local-local") (i32.const 1))

(assert_return (invoke "param-local" (i32.const 1)))
(assert_return (invoke "params-local" (i32.const 1) (i64.const 0)))
(assert_return (invoke "param-locals" (i32.const 1)))
(assert_return (invoke "params-locals" (f32.const 1) (i32.const 0)))
(assert_return (invoke "param-params-locals-local" (f32.const 1) (i32.const 0) (f32.const 1)))

(assert_return (invoke "param-result-local" (i32.const 1)) (f64.const -0))
(assert_return (invoke "params-params-result-locals-locals" (i32.const 1) (i64.const 1) (f32.const 0) (f64.const 1)) (i32.const 1))

